name: package-deploy-release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-release-registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run pack:build
      - run: npm run pack:build:tsc
      - run: mv ./index.ts ./index.d.ts
      - run: rm -rf ./src
      - run: rm -rf ./public
      - run: rm -rf ./.github
      - run: rm -rf ./package-lock.json
      - run: rm -rf ./tailwind.config.js
      - run: rm -rf ./postcss.config.js
      - run: rm -rf ./tsconfig.json
      - run: rm -rf ./tsconfig.package.json
      - run: rm -rf ./build.esbuild.js
      - run: rm -rf ./next.config.js
      - run: rm -rf ./next-env.d.ts
      - run: rm -rf ./.eslintrc.json
      - run: mv ./lib/src ./src
      - run: rm -rf ./lib
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.PACKAGE_PUBLISH_KEY_NPM}}
